Full form bug/icon added
FOSS-Community/website-fossc pull request #231
Opened 2024-01-06 20:31 UTC by praptisharma28

Corrected the full form and added a Linkedin icon in footer to increase the followers!

2024-01-07 10:44 UTC, A91y requested changes

2024-01-07 10:44 UTC, A91y commented on src/components/Footer.jsx
Certain elements in footer are missing. Please fix those.
Original: 
<img width="1267" alt="Screenshot 2024-01-07 160935" src="https://github.com/FOSS-Community/website-fossc/assets/65825207/146afb4e-d28d-4348-bda4-6c402004e19b">

Footer you created:
<img width="1269" alt="Screenshot 2024-01-07 161148" src="https://github.com/FOSS-Community/website-fossc/assets/65825207/b5fddfe6-485b-48e7-bfb7-cc0fe3ae4370">

2024-01-07 16:02 UTC, praptisharma28 commented on src/components/Footer.jsx
Done @A91y , don't know how I missed it.

2024-01-07 16:37 UTC, codecShivam requested changes
![image](https://github.com/FOSS-Community/website-fossc/assets/118369445/cafa41c8-b424-4a62-a76d-3f2b5cc6efa9)

###### @praptisharma28 Ensure that the text regarding 'fosscu' and its open-source components is included, and once that's done, everything lgtm :+1:

2024-01-07 17:12 UTC, praptisharma28 commented
Done @codecShivam

2024-01-08 01:26 UTC, Mr-Sunglasses commented
@praptisharma28 Please open a corresponding issue and link this PR. to that issue it will help us in tracking the progress during releases.

2024-01-08 14:01 UTC, praptisharma28 commented
> @praptisharma28 Please open a corresponding issue and link this PR. to that issue it will help us in tracking the progress during releases.

https://github.com/FOSS-Community/website-fossc/issues/233 @Mr-Sunglasses

2024-01-26 15:55 UTC, closed without merging